apiVersion: v1
kind: Namespace
metadata:
  name: todolist
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todolist-config
  namespace: todolist
data:
  DJANGO_SETTINGS_MODULE: "backend.settings_production"
  DEBUG: "False"
  ALLOWED_HOSTS: "todolist.example.com,localhost"
---
apiVersion: v1
kind: Secret
metadata:
  name: todolist-secret
  namespace: todolist
type: Opaque
data:
  # Base64 encoded values
  SECRET_KEY: ""
  DATABASE_URL: ""
  REDIS_URL: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-web
  namespace: todolist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todolist-web
  template:
    metadata:
      labels:
        app: todolist-web
    spec:
      containers:
      - name: web
        image: todolist:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: todolist-config
              key: DJANGO_SETTINGS_MODULE
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: todolist-secret
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: todolist-secret
              key: DATABASE_URL
        livenessProbe:
          httpGet:
            path: /api/todos/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/todos/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-service
  namespace: todolist
spec:
  selector:
    app: todolist-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todolist-ingress
  namespace: todolist
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: todolist.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todolist-service
            port:
              number: 80